job_scheduler = "Torque"
env_script = "/appli/hibd/rdma-hadoop-2.x-1.3.5-x86/sbin/quick-hadoop-get-env.sh"
outfile = "Job_{}_%j.out"
errfile = "Job_{}_%j.err"

# Defaykt parameters
queue = "omp"
walltime = "12:00:00"
ncpus = 6
mem = "40g"

[Params.Low]
    queue = "omp"
    walltime = "12:00:00"
    ncpus = 1
    mem = "10g"

[Params.High]
    queue = "omp"
    walltime = "12:00:00"
    ncpus = 28
    mem = "120g"